// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	disks "github.com/hashicorp/go-azure-sdk/resource-manager/compute/2022-03-02/disks"
	client "github.com/hashicorp/packer-plugin-azure/builder/azure/common/client"

	galleryimages "github.com/hashicorp/go-azure-sdk/resource-manager/compute/2022-03-03/galleryimages"

	galleryimageversions "github.com/hashicorp/go-azure-sdk/resource-manager/compute/2022-03-03/galleryimageversions"

	images "github.com/hashicorp/go-azure-sdk/resource-manager/compute/2022-03-01/images"

	mock "github.com/stretchr/testify/mock"

	snapshots "github.com/hashicorp/go-azure-sdk/resource-manager/compute/2022-03-02/snapshots"

	virtualmachineimages "github.com/hashicorp/go-azure-sdk/resource-manager/compute/2022-03-01/virtualmachineimages"

	virtualmachines "github.com/hashicorp/go-azure-sdk/resource-manager/compute/2022-03-01/virtualmachines"
)

// AzureClientSet is an autogenerated mock type for the AzureClientSet type
type AzureClientSet struct {
	mock.Mock
}

// DisksClient provides a mock function with given fields:
func (_m *AzureClientSet) DisksClient() disks.DisksClient {
	ret := _m.Called()

	var r0 disks.DisksClient
	if rf, ok := ret.Get(0).(func() disks.DisksClient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(disks.DisksClient)
	}

	return r0
}

// GalleryImageVersionsClient provides a mock function with given fields:
func (_m *AzureClientSet) GalleryImageVersionsClient() galleryimageversions.GalleryImageVersionsClient {
	ret := _m.Called()

	var r0 galleryimageversions.GalleryImageVersionsClient
	if rf, ok := ret.Get(0).(func() galleryimageversions.GalleryImageVersionsClient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(galleryimageversions.GalleryImageVersionsClient)
	}

	return r0
}

// GalleryImagesClient provides a mock function with given fields:
func (_m *AzureClientSet) GalleryImagesClient() galleryimages.GalleryImagesClient {
	ret := _m.Called()

	var r0 galleryimages.GalleryImagesClient
	if rf, ok := ret.Get(0).(func() galleryimages.GalleryImagesClient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(galleryimages.GalleryImagesClient)
	}

	return r0
}

// ImagesClient provides a mock function with given fields:
func (_m *AzureClientSet) ImagesClient() images.ImagesClient {
	ret := _m.Called()

	var r0 images.ImagesClient
	if rf, ok := ret.Get(0).(func() images.ImagesClient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(images.ImagesClient)
	}

	return r0
}

// MetadataClient provides a mock function with given fields:
func (_m *AzureClientSet) MetadataClient() client.MetadataClientAPI {
	ret := _m.Called()

	var r0 client.MetadataClientAPI
	if rf, ok := ret.Get(0).(func() client.MetadataClientAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.MetadataClientAPI)
		}
	}

	return r0
}

// SnapshotsClient provides a mock function with given fields:
func (_m *AzureClientSet) SnapshotsClient() snapshots.SnapshotsClient {
	ret := _m.Called()

	var r0 snapshots.SnapshotsClient
	if rf, ok := ret.Get(0).(func() snapshots.SnapshotsClient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(snapshots.SnapshotsClient)
	}

	return r0
}

// SubscriptionID provides a mock function with given fields:
func (_m *AzureClientSet) SubscriptionID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// VirtualMachineImagesClient provides a mock function with given fields:
func (_m *AzureClientSet) VirtualMachineImagesClient() virtualmachineimages.VirtualMachineImagesClient {
	ret := _m.Called()

	var r0 virtualmachineimages.VirtualMachineImagesClient
	if rf, ok := ret.Get(0).(func() virtualmachineimages.VirtualMachineImagesClient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(virtualmachineimages.VirtualMachineImagesClient)
	}

	return r0
}

// VirtualMachinesClient provides a mock function with given fields:
func (_m *AzureClientSet) VirtualMachinesClient() virtualmachines.VirtualMachinesClient {
	ret := _m.Called()

	var r0 virtualmachines.VirtualMachinesClient
	if rf, ok := ret.Get(0).(func() virtualmachines.VirtualMachinesClient); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(virtualmachines.VirtualMachinesClient)
	}

	return r0
}

type mockConstructorTestingTNewAzureClientSet interface {
	mock.TestingT
	Cleanup(func())
}

// NewAzureClientSet creates a new instance of AzureClientSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAzureClientSet(t mockConstructorTestingTNewAzureClientSet) *AzureClientSet {
	mock := &AzureClientSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
